By this part, you will be able to implement a program where a user can enter simple input, the program can make choices based on some conditions and after calculation, results can be printed.

Goals: 

    1. implement and run your python program in your local machine.

Steps: 

    install Python on your machine.

    Open terminal and check the version of your Python using command : python --version

    Chose your editor to implement a program and save the file in your local machine.

    Execute your firts program.

In [1]:
from platform import python_version
print(python_version())

3.12.2

Assignment 1: Check if a number is even or odd

In this short exercise, you will learn how to:
- Get input from the user
- Check if the input is a valid integer
- Use conditions to decide even or odd

In [2]:
number = int(input ("inter a number: "))

if number % 2 == 0:
    print("That is an even number")
else:
    print("That is an odd number")

That is an even number

input() gets a number from the user.

int() converts it from a string to an integer.

% is the modulo operator (gives remainder).

if num % 2 == 0 checks if the number divides evenly by 2.

Assignment: Ask the user to enter a number and print whether it is even or odd.
If the input is not a valid integer, print an error message.

In [3]:
#assignment: Check if a number is even or odd
user_input = input ("inter a number: ")
try:
    number = int(user_input)
    
    if number % 2 == 0:
        print("That is an even number")
    else:
        print("That is an odd number")
except ValueError:
    print("That is not an integer, please enter a valid integer.")

That is an even number

<h2 style="color:teal;"> What is a Function in Python?</h2>

<p><strong style="color:blue;">A function</strong> is a reusable block of code that performs a specific task. It can take inputs (called arguments) and may return a result.
Here are a few you're already using: </p>

  - print()	 Displays output on the screen	

print("Hello!") → Hello!

   - int()	Converts a value to an integer	int("42") → 42

   - input()	Gets text input from the user	name = input("Enter name: ")

  - type()	Returns the data type of a value	type(5) → <class 'int'>

  - len()	Returns the length of a sequence	len("hello") → 5

In [4]:
print("Hello, World!")

x = int("3")
print("velue of x is", x)  # Outputs: 3

print("data type of x is: ", type(x))  # Outputs: <class 'int'>

print("integer of 4.7 is", int(4.7))  # Outputs: 4

print("x + 2 is", x + 2)  # Outputs: 5

#y = int("abc")  # This will raise a ValueError

Hello, World!
velue of x is 3
data type of x is:  <class 'int'>
integer of 4.7 is 4
x + 2 is 5

In [5]:
#len("hello")  # Outputs: 5
len([1, 2, 3, 4])  # Outputs: 4

4


You can define your own function using the <code style="color:green;">def</code> keyword.

---

<h3 style="color:purple;">Function Syntax</h3>

```python
def function_name(parameters):
    # code block
    return result

 def — keyword to define a function

function_name — the name you choose


parameters — input values to the function


return — (optional) sends a result back   

Assignment 2: create a function that greets a threeon by name.

In [6]:
def greet(name):
    return "Hello, " + name + "! Nice to meet you."

greeting = greet("Alice")
print(greeting)  # Outputs: Hello, Alice!

Hello, Alice! Nice to meet you.

Assignment : <h5 style="color:lightblue;"> Convert Even/Odd Checker into a Function</h5>

In [7]:
def check_even_or_odd(user_input):
    try:
        number = int(user_input)
        if number % 2 == 0:
            print("That is an even number.")
        else:
            print("That is an odd number.")
    except ValueError:
        print("Please enter a valid integer.")

How to use it:

In [8]:
# Ask the user for input
user_input = input("Enter a number: ")

# Call the function with the user's input
check_even_or_odd(user_input)

That is an even number.

In [9]:
text = "Hello world"
text.split()[1]

'world'

In [10]:
list_of_numbers = [1, 2, 3, 4, 5]
list_of_numbers[0:3]

[1, 2, 3]

## How to Debug in Python?

1. Use print() statements

In [11]:
def divide(a, b):
    print("a:", a, "b:", b)
    answer = a / b
    return answer

print(divide(10, 0))  #  ZeroDivisionError
#divide(10, 0)  # This will raise a ZeroDivisionError

a: 10 b: 0

ZeroDivisionError: division by zero

From one value to many values

Earlier: You asked the user to enter one number and checked if it was even or odd.

Now: You read a list of numbers from a CSV file and do the same thing — just at scale.

<p><strong style="color:blue;">Pandas</strong> is a Python library that makes it easy to:

- Work with tables of data

- Read data from CSV files, Excel files, etc.

- Do filtering, sorting, statistics, and more

In [12]:
import pandas as pd

In [13]:
#df = pd.read_excel("Demo-contract.xlsx")
df = pd.read_csv("Demo-contract.csv",sep= ",")
df.head()

,Id,ContractID,PersonID,ContractNumber,EmploymentTypeID,FinancialGroupID,DateStart,ContractHoursPerWeek,ParttimePercentage,DateEnd,Timestamp
0,2,22 1,22,1,Full,3945,01/15/2022 00:00:00,20.0,55.56,NaN,11/17/2025 15:28:10
1,3,22 1,22,1,V,3945,01/01/2022 00:00:00,36.0,100.00,NaN,11/01/2025 14:46:36
2,4,23 1,23,1,Part,3946,01/04/2022 00:00:00,22.6,60.00,NaN,11/04/2025 14:44:16
3,5,23 2,23,2,Full,3945,04/01/2024 00:00:00,14.4,40.00,NaN,11/01/2025 14:46:36
4,6,25 1,25,1,Part,3945,01/10/2022 00:00:00,24.0,66.67,NaN,11/01/2025 14:46:36

In [14]:
#Filter Rows by Column Value
threeon = df[df['PersonID'] == 23]

threeon

,Id,ContractID,PersonID,ContractNumber,ContractTypeID,GroupID,DateStart,ContractHoursPerWeek,ParttimePercentage,DateEnd,Timestamp
2,4,23 1,23,1,Full,3945,01/04/2022 00:00:00,22.6,60.0,NaN,11/04/2025 14:44:16
3,5,23 2,23,2,Part,3945,04/01/2024 00:00:00,14.4,40.0,NaN,11/01/2025 14:46:36

In [15]:
full_time_hours = df[df["ContractHoursPerWeek"] == 36]
full_time_hours

,Id,ContractID,PersonID,ContractNumber,ContractTypeID,GroupID,DateStart,ContractHoursPerWeek,ParttimePercentage,DateEnd,Timestamp
1,3,22 1,22,1,Full,3945,01/01/2022 00:00:00,36.0,100.0,NaN,11/01/2025 14:46:36
5,7,26 1,26,1,T,3945,01/20/2022 00:00:00,36.0,100.0,06/30/2026 00:00:00,11/01/2025 14:46:36

In [16]:
def check_even_or_odd_csv(n):
    if n % 2 == 0:
        return "Even"
    else:
        return "Odd"

In [17]:
#df["odd_or_even"] = df["ContractHoursPerWeek"].apply(lambda x: "Even" if x % 2 == 0 else "Odd")
df['odd_or_even'] = df['ContractHoursPerWeek'].apply(check_even_or_odd_csv)
df.head()

,Id,ContractID,PersonID,ContractNumber,ContractTypeID,GroupID,DateStart,ContractHoursPerWeek,ParttimePercentage,DateEnd,Timestamp,odd_or_even
0,2,22 1,22,1,Part,3945,01/15/2022 00:00:00,20.0,55.56,NaN,11/17/2025 15:28:10,Even
1,3,22 1,22,1,Full,3945,01/01/2022 00:00:00,36.0,100.00,NaN,11/01/2025 14:46:36,Even
2,4,23 1,23,1,Full,3945,01/04/2022 00:00:00,22.6,60.00,NaN,11/04/2025 14:44:16,Odd
3,5,23 2,23,2,Part,3945,04/01/2024 00:00:00,14.4,40.00,NaN,11/01/2025 14:46:36,Odd
4,6,25 1,25,1,Part,3945,01/10/2022 00:00:00,24.0,66.67,NaN,11/01/2025 14:46:36,Even

In [18]:
df['parttimepercent'] =df['ContractHoursPerWeek'].apply(lambda x: round((x / 36.0) * 100))
df.head()

,Id,ContractID,PersonID,ContractNumber,ContractTypeID,GroupID,DateStart,ContractHoursPerWeek,ParttimePercentage,DateEnd,Timestamp,odd_or_even,parttimepercent
0,2,22 1,21,1,Part,3945,01/15/2022 00:00:00,20.0,55.56,NaN,11/17/2025 15:28:10,Even,56
1,3,22 1,22,1,Full,3945,01/01/2022 00:00:00,36.0,100.00,NaN,11/01/2025 14:46:36,Even,100
2,4,23 1,23,1,Full,3945,01/04/2022 00:00:00,22.6,60.00,NaN,11/04/2025 14:44:16,Odd,60
3,5,23 2,23,2,Part,3945,04/01/2024 00:00:00,14.4,40.00,NaN,11/01/2025 14:46:36,Odd,40
4,6,25 1,25,1,Part,3945,01/10/2022 00:00:00,24.0,66.67,NaN,11/01/2025 14:46:36,Even,67

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Id                    8 non-null      int64
 1   ContractID            8 non-null      object
 2   PersonID              8 non-null      int64
 3   ContractNumber        8 non-null      int64
 4   ContractTypeID        8 non-null      object
 5   GroupID               8 non-null      int64
 6   DateStart             8 non-null      object
 7   ContractHoursPerWeek  8 non-null      float64
 8   ParttimePercentage    8 non-null      float64
 9   DateEnd               3 non-null      object
 10  Timestamp             8 non-null      object
 11  odd_or_even           8 non-null      object
 12  parttimepercent       8 non-null      int64
dtypes: float64(2), int64(5), object(6)
memory usage: 964.0+ bytes

In [20]:
output = df.to_csv("Demo-contract-modified.csv", index=False)

In [22]:
import rdflib
from rdflib import Graph, Literal, RDF, URIRef, Namespace
from rdflib.namespace import RDFS, XSD

In [22]:
default_namespace = "http://example.org#"  # Replace with your desired namespace

# Define common namespace URIs
#version = 3.0.0

onz_one_s = 'http://purl.org/ozo/onz-org#'
onz_one_ns = Namespace(onz_org_s)
onz_two_s = 'http://purl.org/ozo/onz-g#'
onz_two_ns = Namespace(onz_two_s)
onz_three_s = 'http://purl.org/ozo/onz-three#'
onz_three_ns = Namespace(onz_three_s)

In [23]:
g = rdflib.Graph()

In [24]:
# Bind the namespace as the default namespace
g.bind("", default_namespace)
g.bind('onz-one', onz_one_ns)
g.bind('onz-two', onz_two_ns)
g.bind('onz-three', onz_three_ns)

In [25]:
headers = df.columns.tolist()
for index, row in df.iterrows():
    try:
        # Validate required fields exist
        if pd.isna(row['ContractID']):
            print(f"Row {index} skipped: 'ContractID' is missing.")
            continue

        # Direct column access and replace spaces with underscores
        contract_id = str(row['ContractID']).strip().replace(' ', '_')           
        contract_uri = URIRef(f"{default_namespace}Agreement_{contract_id}")

        employee_id = str(row['PersonID']).strip().replace(' ', '_') if pd.notna(row['PersonID']) else "Unknown"
        employee_uri = URIRef(f"{default_namespace}Employee_{employee_id}")
        g.add((employee_uri, RDFS.label, Literal(employee_id, datatype=XSD.string)))


        date_start = row['DateStart'] if pd.notna(row['DateStart']) else None
        date_end = row['DateEnd'] if pd.notna(row['DateEnd']) else None
        g.add((contract_uri, onz_two_ns.startDatum, Literal(date_start, datatype=XSD.date)))
        if date_end:
            g.add((contract_uri, onz_two_ns.eindDatum, Literal(date_end, datatype=XSD.date)))

        
        # Add to RDF graph
        g.add((contract_uri, RDF.type, onz_three_ns.Type))
        g.add((contract_uri, onz_three_ns.employee, employee_uri))
        g.add((employee_uri, RDF.type, onz_three_ns.Human))
        
        print(f"Processed row {index} successfully.")
       
    except Exception as e:
        print(f"Error processing row {index}: {e}")

Processed row 0 successfully.
Processed row 1 successfully.
Processed row 2 successfully.
Processed row 3 successfully.
Processed row 4 successfully.
Processed row 5 successfully.
Processed row 6 successfully.
Processed row 7 successfully.

In [26]:
# Save the RDF graph to a TTL file
output_file = "contract_data.ttl"
g.serialize(destination=output_file, format='turtle')
print(f"RDF graph saved to {output_file}")

# Optional: Print the TTL content to see what was generated
print("\nGenerated TTL content:")
print(g.serialize(format='turtle'))

RDF graph saved to contract_data.ttl

Generated TTL content:
@prefix : <http://example.org#> .
@prefix onz-g: <http://purl.org/onz-two#> .
@prefix onz-three: <http://purl.org/onz-three#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:Agreement_21_1 a onz-three:Type ;
    onz-g:startDatum "0101-01-01"^^xsd:date ;
    onz-three:employee :Employee_21 .

:Agreement_22_1 a onz-three:Type ;
    onz-g:startDatum "0101-01-01"^^xsd:date ;
    onz-three:employee :Employee_22 .

:Agreement_23_1 a onz-three:Type ;
    onz-g:startDatum "0101-01-01"^^xsd:date ;
    onz-three:employee :Employee_23 .

:Agreement_23_2 a onz-three:Type ;
    onz-g:startDatum "0401-01-01"^^xsd:date ;
    onz-three:employee :Employee_23 .

:Agreement_25_1 a onz-three:Type ;
    onz-g:startDatum "0101-01-01"^^xsd:date ;
    onz-three:employee :Employee_25 .

:Agreement_26_1 a onz-three:Type ;
    onz-g:eindDatum "0601-01-01"^^xsd:date ;
    onz-g:startDatum "0101-01-01"^^xsd:date ;
    onz-three:employee :Employee_26 .

:Agreement_26_2 a onz-three:Type ;
    onz-g:eindDatum "1201-01-01"^^xsd:date ;
    onz-g:startDatum "0101-01-01"^^xsd:date ;
    onz-three:employee :Employee_26 .

:Agreement_27_1 a onz-three:Type ;
    onz-g:eindDatum "1201-01-01"^^xsd:date ;
    onz-g:startDatum "0101-01-01"^^xsd:date ;
    onz-three:employee :Employee_27 .

:Employee_21 a onz-three:Human ;
    rdfs:label "21"^^xsd:string .

:Employee_22 a onz-three:Human ;
    rdfs:label "22"^^xsd:string .

:Employee_25 a onz-three:Human ;
    rdfs:label "25"^^xsd:string .

:Employee_27 a onz-three:Human ;
    rdfs:label "27"^^xsd:string .

:Employee_23 a onz-three:Human ;
    rdfs:label "23"^^xsd:string .

:Employee_26 a onz-three:Human ;
    rdfs:label "26"^^xsd:string .