By this part, you will be able to implement a program where a user can enter simple input, the program can make choices based on some conditions and after calculation, results can be printed.

Goals: 

    1. implement and run your python program in your local machine.

Steps: 

    install Python on your machine.

    Open terminal and check the version of your Python using command : python --version

    Chose your editor to implement a program and save the file in your local machine.

    Execute your firts program.

In [1]:
from platform import python_version
print(python_version())

3.12.2

Assignment 1: Check if a number is even or odd

In this short exercise, you will learn how to:
- Get input from the user
- Check if the input is a valid integer
- Use conditions to decide even or odd

In [11]:
number = int(input ("inter a number: "))

if number % 2 == 0:
    print("That is an even number")
else:
    print("That is an odd number")

That is an odd number

input() gets a number from the user.

int() converts it from a string to an integer.

% is the modulo operator (gives remainder).

if num % 2 == 0 checks if the number divides evenly by 2.

Assignment: Ask the user to enter a number and print whether it is even or odd.
If the input is not a valid integer, print an error message.

In [13]:
#assignment: Check if a number is even or odd
user_input = input ("inter a number: ")
try:
    number = int(user_input)
    
    if number % 2 == 0:
        print("That is an even number")
    else:
        print("That is an odd number")
except ValueError:
    print("That is not an integer, please enter a valid integer.")

That is an even number

<h2 style="color:teal;"> What is a Function in Python?</h2>

<p><strong style="color:blue;">A function</strong> is a reusable block of code that performs a specific task. It can take inputs (called arguments) and may return a result.
Here are a few you're already using: </p>

  - print()	 Displays output on the screen	

print("Hello!") → Hello!

   - int()	Converts a value to an integer	int("42") → 42

   - input()	Gets text input from the user	name = input("Enter name: ")

  - type()	Returns the data type of a value	type(5) → <class 'int'>

  - len()	Returns the length of a sequence	len("hello") → 5

In [14]:
print("Hello, World!")

x = int("3")
print("velue of x is", x)  # Outputs: 3

print("data type of x is: ", type(x))  # Outputs: <class 'int'>

print("integer of 4.7 is", int(4.7))  # Outputs: 4

print("x + 2 is", x + 2)  # Outputs: 5

#y = int("abc")  # This will raise a ValueError

Hello, World!
velue of x is 3
data type of x is:  <class 'int'>
integer of 4.7 is 4
x + 2 is 5

In [15]:
#len("hello")  # Outputs: 5
len([1, 2, 3, 4])  # Outputs: 4

4


You can define your own function using the <code style="color:green;">def</code> keyword.

---

<h3 style="color:purple;">Function Syntax</h3>

```python
def function_name(parameters):
    # code block
    return result

 def — keyword to define a function

function_name — the name you choose


parameters — input values to the function


return — (optional) sends a result back   

Assignment 2: create a function that greets a person by name.

In [17]:
def greet(name):
    return "Hello, " + name + "! Nice to meet you."

greeting = greet("Job")
print(greeting)  # Outputs: Hello, Alice!

Hello, Job! Nice to meet you.

Assignment : <h5 style="color:lightblue;"> Convert Even/Odd Checker into a Function</h5>

In [19]:
def check_even_or_odd(user_input):
    try:
        number = int(user_input)
        if number % 2 == 0:
            print("That is an even number.")
        else:
            print("That is an odd number.")
    except ValueError:
        print("Please enter a valid integer.")

How to use it:

In [20]:
# Ask the user for input
user_input = input("Enter a number: ")

# Call the function with the user's input
check_even_or_odd(user_input)

That is an odd number.

In [22]:
text = "Hello world"
text.split()[0]

'Hello'

In [23]:
list_of_numbers = [1, 2, 3, 4, 5]
list_of_numbers[0:3]

[1, 2, 3]

In [24]:
#i=0
for i in list_of_numbers:
    print(i)

1
2
3
4
5

## How to Debug in Python?

1. Use print() statements

In [26]:
def divide(a, b):
    print("a:", a, "b:", b)
    answer = a / b
    return answer

print(divide(10, 0))  #  ZeroDivisionError
#divide(10, 0)  # This will raise a ZeroDivisionError

a: 10 b: 0

ZeroDivisionError: division by zero

From one value to many values

Earlier: You asked the user to enter one number and checked if it was even or odd.

Now: You read a list of numbers from a CSV file and do the same thing — just at scale.

<p><strong style="color:blue;">Pandas</strong> is a Python library that makes it easy to:

- Work with tables of data

- Read data from CSV files, Excel files, etc.

- Do filtering, sorting, statistics, and more

In [28]:
import pandas as pd

In [29]:
#df = pd.read_excel("Demo-contract.xlsx")
df = pd.read_csv("Demo-workshop.csv",sep= ",")
df.head()

,ContractBK,PersonBK,StartDate,EndDate,HoursPerWeek,FunctionCode,LocationCode
0,C-001,1001,2024-01-01,2024-12-31,36,NURSE,L1
1,C-002,1002,2024-02-01,2024-12-31,32,ADMIN,L2
2,C-003,1003,2024-03-01,NaN,28,NURSE,L1

In [30]:
#Filter Rows by Column Value
person = df[df['PersonBK'] == 1001]

person

,ContractBK,PersonBK,StartDate,EndDate,HoursPerWeek,FunctionCode,LocationCode
0,C-001,1001,2024-01-01,2024-12-31,36,NURSE,L1

In [31]:
full_time_hours = df[df["HoursPerWeek"] == 36]
full_time_hours

,ContractBK,PersonBK,StartDate,EndDate,HoursPerWeek,FunctionCode,LocationCode
0,C-001,1001,2024-01-01,2024-12-31,36,NURSE,L1

In [33]:
def check_even_or_odd_csv(n):
    if n % 2 == 0:
        return "Even"
    else:
        return "Odd"

In [34]:
#df["odd_or_even"] = df["HoursPerWeek"].apply(lambda x: "Even" if x % 2 == 0 else "Odd")
df['odd_or_even'] = df['HoursPerWeek'].apply(check_even_or_odd_csv)
df.head()

,ContractBK,PersonBK,StartDate,EndDate,HoursPerWeek,FunctionCode,LocationCode,odd_or_even
0,C-001,1001,2024-01-01,2024-12-31,36,NURSE,L1,Even
1,C-002,1002,2024-02-01,2024-12-31,32,ADMIN,L2,Even
2,C-003,1003,2024-03-01,NaN,28,NURSE,L1,Even

In [8]:
df['parttimepercent'] =df['HoursPerWeek'].apply(lambda x: round((x / 36.0) * 100))
df.head()

,ContractBK,PersonBK,StartDate,EndDate,HoursPerWeek,FunctionCode,LocationCode,odd_or_even,parttimepercent
0,C-001,1001,2024-01-01,2024-12-31,36,NURSE,L1,Even,100
1,C-002,1002,2024-02-01,2024-12-31,32,ADMIN,L2,Even,89
2,C-003,1003,2024-03-01,NaN,28,NURSE,L1,Even,78

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ContractBK       3 non-null      object
 1   PersonBK         3 non-null      int64
 2   StartDate        3 non-null      object
 3   EndDate          2 non-null      object
 4   HoursPerWeek     3 non-null      int64
 5   FunctionCode     3 non-null      object
 6   LocationCode     3 non-null      object
 7   odd_or_even      3 non-null      object
 8   parttimepercent  3 non-null      int64
dtypes: int64(3), object(6)
memory usage: 348.0+ bytes

In [10]:
output = df.to_csv("Demo-workshop-modified.csv", index=False)

In [35]:
import rdflib
from rdflib import Graph, Literal, RDF, URIRef, Namespace
from rdflib.namespace import RDFS, XSD

In [36]:
# Define common namespace URIs
#version = 3.0.0
schema = Namespace('https://schema.org/#')
ex = Namespace('http://example.org/id#')

In [37]:
g = rdflib.Graph()

In [38]:
# Bind the namespace as the default namespace
g.bind("schema", schema)
g.bind("ex", ex)

In [39]:
df_people = pd.read_csv("people.csv", sep= ";")
df_people.head()

   id       name              email   birthdate
0   1  Alice Doe  alice@example.org  12/04/1990
1   2  Bob Smith    bob@example.org  30/10/1985

In [40]:
df_events= pd.read_csv("events.csv",sep=";")
df_events.head()

  event_id            title        date  organiser_id
0     E100  Health Workshop  01/03/2024             1
1     E101      Data Summit  15/05/2024             2

In [41]:
headers = df_people.columns.tolist()
for index, row in df_people.iterrows():
    try:
        # Validate required fields exist
        if pd.isna(row['name']):
            print(f"Row {index} skipped: 'name' missing.")
            continue

        person_uri = ex[f"person/{row['id']}"]
        g.add((person_uri, RDF.type, schema.Person))
        g.add((person_uri, schema.name, Literal(row["name"])))
        g.add((person_uri, schema.email, Literal(row["email"])))
        g.add((person_uri, schema.birthDate, Literal(row["birthdate"], datatype=XSD.date)))
        print(f"Processed row {index} successfully.")
        
              
    except Exception as e:
        print(f"Error processing row {index}: {e}")

Processed row 0 successfully.
Processed row 1 successfully.

In [42]:
headers= df_events.columns.tolist()
for index, row in df_events.iterrows():
    try:
        # Validate required fields exist
        if pd.isna(row['title']):
            print(f"Row {index} skipped: 'title' missing.")
            continue

        event_uri = URIRef(f"{ex}event_{row['event_id']}")
        g.add((event_uri, RDF.type, schema.Event))
        g.add((event_uri, schema.name, Literal(row["title"])))
        g.add((event_uri, schema.startDate, Literal(row["date"], datatype=XSD.date)))

        organiser_uri = ex[f"person/{row['organiser_id']}"]
        g.add((event_uri, schema.organizer, organiser_uri))
        print(f"Processed row {index} successfully.")
        
              
    except Exception as e:
        print(f"Error processing row {index}: {e}")

Processed row 0 successfully.
Processed row 1 successfully.

In [43]:
# Save the RDF graph to a TTL file
output_file = "events_data.ttl"
g.serialize(destination=output_file, format='turtle')
print(f"RDF graph saved to {output_file}")

# Optional: Print the TTL content to see what was generated
print("\nGenerated TTL content:")
print(g.serialize(format='turtle'))

RDF graph saved to events_data.ttl

Generated TTL content:
@prefix ex: <http://example.org/id#> .
@prefix schema1: <https://schema.org/#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:event_E100 a schema1:Event ;
    schema1:name "Health Workshop" ;
    schema1:organizer <http://example.org/id#person/1> ;
    schema1:startDate "0101-01-01"^^xsd:date .

ex:event_E101 a schema1:Event ;
    schema1:name "Data Summit" ;
    schema1:organizer <http://example.org/id#person/2> ;
    schema1:startDate "1501-01-01"^^xsd:date .

<http://example.org/id#person/1> a schema1:Person ;
    schema1:birthDate "1201-01-01"^^xsd:date ;
    schema1:email "alice@example.org" ;
    schema1:name "Alice Doe" .

<http://example.org/id#person/2> a schema1:Person ;
    schema1:birthDate "3001-01-01"^^xsd:date ;
    schema1:email "bob@example.org" ;
    schema1:name "Bob Smith" .